version: '3'
services:
  web:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: python /app/main.py
  socket:
    build: .
    ports:
      - "5001:5001"
    command: python /app/socket_server.py
    volumes:
      - .:/app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db